- name: verify pip is installed
  apt:
    name: python-pip
    state: present

- name: install elasticsearch-curator 4
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - elasticsearch-curator

- name: create /etc/elasticsearch-curator directory
  file:
    path: /etc/elasticsearch-curator
    state: directory
    mode: 0755

- name: copy elasticsearch-curator config
  copy:
    content: "{{ elasticsearch_curator_config }}"
    dest: /etc/elasticsearch-curator/curator.yml
    mode: 0755

- name: copy elasticsearch-curator actions
  copy:
    content: "{{ elasticsearch_curator_actions }}"
    dest: /etc/elasticsearch-curator/actions.yml
    mode: 0755

- name: Configure cron jobs for Elasticsearch Curator.
  cron:
    name: "{{ item.name }}"
    job: "{{ item.job }}"
    minute: "{{ item.minute | default('*') }}"
    hour: "{{ item.hour | default('*') }}"
    day: "{{ item.day | default('*') }}"
    weekday: "{{ item.weekday | default('*') }}"
    month: "{{ item.month | default('*') }}"
  with_items: "{{ elasticsearch_curator_crontab }}"
